name: Biên dịch AssemblyCSharpPreprocessor
on: 
  workflow_dispatch:

jobs:
  build:
    name: Biên dịch AssemblyCSharpPreprocessor
    runs-on: windows-latest
    env:
      Solution_Name: AssemblyCSharpPreprocessor.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: AssemblyCSharpPreprocessor
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
    - name: Restore
      run: |
        msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
        nuget restore $env:Solution_Name
    - name: Build
      run: msbuild $env:Solution_Name -t:rebuild -property:Configuration=Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AssemblyCSharpPreprocessor
        path: bin/Release